# Generated by Django 4.2.4 on 2024-09-14 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('three_facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threefacts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threefacts',
            name='topic_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='three_facts.topiccategory'),
        ),
        migrations.AddField(
            model_name='threefacts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
